### ISSUE TITLE
Inconsistent line breaks around fenced code blocks

### ISSUE THREAD

**Issue by t-rad679** [vsch/idea-multimarkdown#770]
I'm finding that when I format my document, I get inconsistent line breaks following fenced code blocks, and it seems to be related to list indentation. If the next list item after the code block is an indentation level deeper, I see an extra line; otherwise, I do not. It also does not seem to care about the preceding line break. For example:

__\* stuff__

  __\```
  foo.code
  \```__

\<two space indent\>__\* bar__

and

__\* stuff__

  __\```
  foo.code
  \```
  \* bar__

Is there a solution to this issue?

**Comment by t-rad679** [comment]
neither of those cases are what I'm seeing. I formatted them differently in the comment by accident than the way they're formatted in my code. The spaces on the second item are also not removed for me.

The biggest problem is the following:

    1. a
      * b

        ```bash
        foo.code
        ```

      * c


becomes


    1. a
      * b

        ```bash
        foo.code
        ```
      * c


after formatting. See that the code snippet is aligned properly with the text of the bullet. This should make the next bullet count as the same list, right?

The other weird part is that 


    1. a
      * b

        ```bash
        foo.code
        ```

        * c


stays exactly the same after formatting.

**Comment by vsch** [comment]
@t-rad679, I am going to make an EAP build with a fix for export markdown settings action that will include markdown code style settings. That way you will be able to export your markdown settings and I will be able to import them on my side and validate all the settings, including ones for formatting.

I also found a "bug" for inspections that I fixed. Mainly, there is an inspection that will flag improperly indented items. However, for CommonMark your case was not flagged because the items are in different lists as per CommonMark rules (switching ordered/unordered items starts a new list). Now the inspection will take items of consecutive lists regardless of their type differences. You will see the following for your list:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/10299086/63899006-36697080-c9c9-11e9-8219-13c8a4a2600f.png">

I will update this issue as soon as the EAP build is available.

**Comment by vsch** [comment]
@t-rad679, thank you for your patience and persistence. I appreciate the effort you took to report the issue and have it understood correctly.

I think the issue is fixed in the EAP release. It was caused by incorrect loose list item determination. The formatting for lists by default has lists formatting as "Loose if has loose item" the bug was causing the list to appear as a tight list and caused it to delete all trailing blank lines after list items. So the blank line after the fenced code was being deleted due to that.

However, if you still have issues please let me know.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by t-rad679** [comment]
Thank you so much! I'll try it out right away!

**Comment by t-rad679** [comment]
Can you confirm the fix is in v2.9.7.8? I changed my update settings to EAP, performed the update, and restarted IntelliJ, but I am still seeing the same behavior.

**Comment by t-rad679** [comment]
I just tried changing my list settings to "Lose if has loose item". That fixed it. Is there a way to keep lists tight, but still enforce that code blocks are surrounded on both sides by a blank line?

**Comment by vsch** [comment]
@t-rad679, commonmark/markdown loose/tight list determination is quirky for human eyes. So trying to keep blank lines around fenced code or other child elements of lists, will make a loose item out of a tight item.

What happens if you select "No Change" for list loose/tight setting in formatter? 

This options should not change your blank lines around items or child items so you can control this manually.

I will see if I can add the option to fenced-code blocks to put blank lines around them. It might be harder than it sounds because being in a list item causes the parent to control the blank lines around their child elements. I will have to try it out.

I added a separate issue for it #774.

**Comment by t-rad679** [comment]
That works as well.  Thank you for your help!

**Comment by t-rad679** [comment]
I just discovered that I'm still having a similar issue with list bullets that have reduced indent after a fenced code block. To be specific,

    * stuff
      * more stuff

        ```bash
        foo.code
         ```
    * bar

does not change on format to

    * stuff
      * more stuff

        ```bash
        foo.code
         ```

    * bar

However, it also does not change on format to:

    * stuff
      * more stuff
        ```bash
        foo.code
         ```
    * bar


This part of the behavior is correct.

**Comment by vsch** [comment]
@t-rad679, welcome to Markdown and CommonMark lists.

All three are different beasts.

1. Is a two item tight list with single item loose sublist

   ```
   * stuff
     * more stuff

       ```bash
       foo.code
        ```
   * bar
   ```

   ```html
   <ul>
     <li>stuff
       <ul>
         <li>
           <p>more stuff</p>
           <pre><code class="language-bash">foo.code
   </code></pre>
         </li>
       </ul>
     </li>
     <li>bar</li>
   </ul>
   ```

2. Is a two item loose list with single item loose sublist

   ```
   * stuff
     * more stuff

       ```bash
       foo.code
        ```

   * bar
   ```

   ```html
   <ul>
     <li>
       <p>stuff</p>
       <ul>
         <li>
           <p>more stuff</p>
           <pre><code class="language-bash">foo.code
   </code></pre>
         </li>
       </ul>
     </li>
     <li>
       <p>bar</p>
     </li>
   </ul>
   ```

3. Is a two item tight list with single item tight sublist

   ```
   * stuff
     * more stuff
       ```bash
       foo.code
        ```
   * bar
   ```

   ```html
   <ul>
     <li>stuff
       <ul>
         <li>more stuff
           <pre><code class="language-bash">foo.code
   </code></pre>
         </li>
       </ul>
     </li>
     <li>bar</li>
   </ul>
   ```

On #775, I did provide links to help you with better understanding of CommonMark: [CommonMark (spec 0.28)][]

And a great tool to show how markdown is rendered by different processors. It will show the difference a blank line can make: [https://babelmark.github.io][]

I think you need to take a bit more time to appreciate that markdown is not as straight forward as would seem at first glance and certainly is counter intuitive in many cases. Please try your markdown on [https://babelmark.github.io] to validate your expectations.

[CommonMark (spec 0.28)]: https://spec.commonmark.org/0.28
[https://babelmark.github.io]: https://babelmark.github.io

**Comment by t-rad679** [comment]
So it's not possible to configure the formatter to consistently add the expected blank line after the fenced code block? It is convention to have blank lines on either side of a fenced code block, correct?

**Comment by vsch** [comment]
@t-rad679, not if it is the first or last child of a list item because then the blank lines around it have list loose/tight significance which makes these blank lines a list concern not fenced code concern.

I added an enhancement issue #775 to add a setting either to `Fenced Code` or `Lists` to force blank lines around fenced code even when in list items.

Keep in mind that this would make the list a loose list. In CommonMark a list with a single loose item becomes a loose list.

**Comment by t-rad679** [comment]
Okay, that makes sense. I will take some time to dive more deeply into the nuances of Markdown, as per your suggestions. Thank you for all your help!

**Comment by vsch** [comment]
@t-rad679, you are welcome.
