### ISSUE TITLE
old licensing key not work when update to v3

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#814]
old licensing key not work when update to v3

**Comment by starwarsfan** [comment]
Same here. I've renewed my license two months ago but now I'm unable to use it as I always got the message "Key is invalid". How to ahead now?

**Comment by vsch** [comment]
The latest plugin defaults to using JetBrains Marketplace license which is activated by the IDE.

To continue using your current non-JetBrains license:

1. After upgrading to the new plugin version select “Evaluate for free” in the license activation for Markdown Navigator so the IDE loads and runs the new plugin using JetBrains licensing.
2. The next time you restart the IDE, after about 15 seconds, the plugin will detect a legacy license and offer to switch to the legacy update channel.
3. The next time IDE checks for plugin updates, it will prompt you to upgrade Markdown Navigator Enhance to the version on the legacy update channel. The legacy update channel has a plugin which does not use the JetBrains license and will use your current license.

If you don’t have automatic updates enabled you will need to check for updates manually before the 30 days evaluation expires, otherwise you will need to download and install the plugin from the Legacy channel from JetBrains plugin page manually since the IDE disables plugins without a valid JetBrains Marketplace license.

**Comment by bluelovers** [comment]
thx, looks like it still didn't auto detect for me

![image](https://user-images.githubusercontent.com/167966/73789192-49366b80-47d9-11ea-8142-c8c62196b834.png)

but i found option switch it by self

**Comment by vsch** [comment]
@bluelovers, I am glad this is resolved for you.

If you have "EAP" channel, the plugin still detects the channel and maps it to "EAP - Legacy", otherwise to "Legacy". I will double check but I did test this condition and it worked.

**Comment by jshook** [comment]
This is still broken for me. I just accepted the EAP channel updates as it looked like all my essential plugins were now supported., but it disabled the plugin before IntelliJ started it's main init.
I switched it to "preview for 30 days" and only after this does it seem to detect the legacy license format and prompt for changing the update channel.

**Comment by vsch** [comment]
@jshook, there are two EAP channels for the plugin. One for the JetBrains licensed version and the other for Legacy.

Go into settings, Languages & Frameworks | Markdown and select the Legacy EAP channel.

Stable and EAP have JetBrains plugins which is what you have installed since the IDE activates it.

**Comment by Tecktron** [comment]
@vsch When I open IntelliJ today, I get a License Activation window. 

I have a valid license that was sent to me in email (318 days valid). 
Where do I go from here as nothing seems to work?

![image](https://user-images.githubusercontent.com/4650904/77432651-bc5d6680-6db4-11ea-9730-7552cc3bb084.png)

**Comment by vsch** [comment]
@Tecktron,

The evaluation period for JetBrains licensed plugin is expired, so the plugin is not loaded. You should follow the second set of instructions to install the Legacy plugin manually.

The standard and EAP channels have plugins which use JetBrains licensing which is managed by the IDE. The Legacy and Legacy EAP have plugins which do not use JetBrains licensing and instead manage licensing using legacy license. So in your case you need to install the Legacy plugin manually.

1. Download a new version of the plugin from one of the Legacy channels on the plugin page in [JetBrains plugin page][].
   
   ![image](https://user-images.githubusercontent.com/10299086/77655295-95379e00-6f48-11ea-90ca-bfd9bc9a3a17.png)

   The plugin updated from these channels will recognize your legacy license.

2. Install the downloaded file by going to Plugins in settings and using the settings menu to "Install Plugin from disk..."

3. Restart the IDE

4. If the plugin detects that there is no legacy license on startup and offers to switch to Regular update channel. Select "Do Not Change Update Channel".

5. The plugin will now allow entering the non-JetBrains license under Languages \& Frameworks \| Markdown.

6. When the plugin detects a legacy license startup and offers to switch to Legacy update channel, select "Switch Update Channel" to ensure that future updates use the legacy license.

The update channel can be changed manually, under Languages \& Frameworks \| Markdown. Updates from one of the Legacy channels will ensure that updated versions of the plugin will continue to use the legacy license.

[JetBrains plugin page]: https://plugins.jetbrains.com/idea/plugin/7896-markdown-navigator-enhanced
