### ISSUE TITLE
Images fail to render in preview

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#90]
.PNG link reference resolves, but does not render in the preview panel:

![image](https://cloud.githubusercontent.com/assets/175716/11932397/2c24f440-a7c3-11e5-911f-c61fbbe2dc27.png)

**Comment by vsch** [comment]
@breandan, this one appears to have been fixed by #88. I am running the fixed version and it all resolved and displays in all link formats. Let me know if it is the same on your system.

**Comment by breandan** [comment]
Verified #88 fixed, but PNG rendering still appears broken:

![image](https://cloud.githubusercontent.com/assets/175716/11988205/0ada2258-a9ba-11e5-8bd2-d36b4b57f9de.png)

Also broken for GIF rendering: 

![image](https://cloud.githubusercontent.com/assets/175716/11988228/869a886a-a9ba-11e5-84bb-75d790a863d8.png)

And JPG:

![image](https://cloud.githubusercontent.com/assets/175716/11988222/6bf75fe2-a9ba-11e5-97bd-c3720dfc80a6.png)

**Comment by vsch** [comment]
@breandan, I fixed a few more bugs with link resolution but will verify these to make sure  they work before I make the next release. The next release will be  a bug fix release so it should happen in a few days.

**Comment by vsch** [comment]
@breandan, this is confirmed fixed for next release. If you need it sooner then let me know, I'll make a build with this and other fixes as an unofficial release. :)

**Comment by vsch** [comment]
@breandan, Latest interim release with fixes for exceptions and some feature additions <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.9.zip>

Have a Merry Christmas and Happy Holidays.
